/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

/**
 *
 * @author Caio Gabriel
 */
public class teste extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_a1 = new javax.swing.JButton();
        bt_a2 = new javax.swing.JButton();
        bt_a3 = new javax.swing.JButton();
        bt_a4 = new javax.swing.JButton();
        bt_a5 = new javax.swing.JButton();
        bt_b1 = new javax.swing.JButton();
        bt_b2 = new javax.swing.JButton();
        bt_b3 = new javax.swing.JButton();
        bt_b4 = new javax.swing.JButton();
        bt_b5 = new javax.swing.JButton();
        bt_c1 = new javax.swing.JButton();
        bt_c2 = new javax.swing.JButton();
        bt_c3 = new javax.swing.JButton();
        bt_c4 = new javax.swing.JButton();
        bt_c5 = new javax.swing.JButton();
        bt_d1 = new javax.swing.JButton();
        bt_d2 = new javax.swing.JButton();
        bt_d3 = new javax.swing.JButton();
        bt_d4 = new javax.swing.JButton();
        bt_d5 = new javax.swing.JButton();
        bt_e1 = new javax.swing.JButton();
        bt_e2 = new javax.swing.JButton();
        bt_e3 = new javax.swing.JButton();
        bt_e4 = new javax.swing.JButton();
        bt_e5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bt_f1 = new javax.swing.JButton();
        bt_f2 = new javax.swing.JButton();
        bt_f3 = new javax.swing.JButton();
        bt_f4 = new javax.swing.JButton();
        bt_f5 = new javax.swing.JButton();
        bt_g1 = new javax.swing.JButton();
        bt_g2 = new javax.swing.JButton();
        bt_g3 = new javax.swing.JButton();
        bt_g4 = new javax.swing.JButton();
        bt_g5 = new javax.swing.JButton();
        bt_h1 = new javax.swing.JButton();
        bt_h2 = new javax.swing.JButton();
        bt_h3 = new javax.swing.JButton();
        bt_h4 = new javax.swing.JButton();
        bt_h5 = new javax.swing.JButton();
        bt_i1 = new javax.swing.JButton();
        bt_i2 = new javax.swing.JButton();
        bt_i3 = new javax.swing.JButton();
        bt_i4 = new javax.swing.JButton();
        bt_i5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel4.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel5.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(350, 385));
        jPanel2.setLayout(new java.awt.GridLayout(5, 5));
        jPanel2.add(bt_a1);
        jPanel2.add(bt_a2);
        jPanel2.add(bt_a3);
        jPanel2.add(bt_a4);
        jPanel2.add(bt_a5);
        jPanel2.add(bt_b1);
        jPanel2.add(bt_b2);
        jPanel2.add(bt_b3);
        jPanel2.add(bt_b4);
        jPanel2.add(bt_b5);
        jPanel2.add(bt_c1);
        jPanel2.add(bt_c2);
        jPanel2.add(bt_c3);
        jPanel2.add(bt_c4);
        jPanel2.add(bt_c5);
        jPanel2.add(bt_d1);
        jPanel2.add(bt_d2);
        jPanel2.add(bt_d3);
        jPanel2.add(bt_d4);
        jPanel2.add(bt_d5);
        jPanel2.add(bt_e1);
        jPanel2.add(bt_e2);
        jPanel2.add(bt_e3);
        jPanel2.add(bt_e4);
        jPanel2.add(bt_e5);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(350, 385));
        jPanel3.setLayout(new java.awt.GridLayout(5, 5));
        jPanel3.add(bt_f1);
        jPanel3.add(bt_f2);
        jPanel3.add(bt_f3);
        jPanel3.add(bt_f4);
        jPanel3.add(bt_f5);
        jPanel3.add(bt_g1);
        jPanel3.add(bt_g2);
        jPanel3.add(bt_g3);
        jPanel3.add(bt_g4);
        jPanel3.add(bt_g5);
        jPanel3.add(bt_h1);
        jPanel3.add(bt_h2);
        jPanel3.add(bt_h3);
        jPanel3.add(bt_h4);
        jPanel3.add(bt_h5);
        jPanel3.add(bt_i1);
        jPanel3.add(bt_i2);
        jPanel3.add(bt_i3);
        jPanel3.add(bt_i4);
        jPanel3.add(bt_i5);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(0, 51, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 385));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_a1;
    private javax.swing.JButton bt_a2;
    private javax.swing.JButton bt_a3;
    private javax.swing.JButton bt_a4;
    private javax.swing.JButton bt_a5;
    private javax.swing.JButton bt_b1;
    private javax.swing.JButton bt_b2;
    private javax.swing.JButton bt_b3;
    private javax.swing.JButton bt_b4;
    private javax.swing.JButton bt_b5;
    private javax.swing.JButton bt_c1;
    private javax.swing.JButton bt_c2;
    private javax.swing.JButton bt_c3;
    private javax.swing.JButton bt_c4;
    private javax.swing.JButton bt_c5;
    private javax.swing.JButton bt_d1;
    private javax.swing.JButton bt_d2;
    private javax.swing.JButton bt_d3;
    private javax.swing.JButton bt_d4;
    private javax.swing.JButton bt_d5;
    private javax.swing.JButton bt_e1;
    private javax.swing.JButton bt_e2;
    private javax.swing.JButton bt_e3;
    private javax.swing.JButton bt_e4;
    private javax.swing.JButton bt_e5;
    private javax.swing.JButton bt_f1;
    private javax.swing.JButton bt_f2;
    private javax.swing.JButton bt_f3;
    private javax.swing.JButton bt_f4;
    private javax.swing.JButton bt_f5;
    private javax.swing.JButton bt_g1;
    private javax.swing.JButton bt_g2;
    private javax.swing.JButton bt_g3;
    private javax.swing.JButton bt_g4;
    private javax.swing.JButton bt_g5;
    private javax.swing.JButton bt_h1;
    private javax.swing.JButton bt_h2;
    private javax.swing.JButton bt_h3;
    private javax.swing.JButton bt_h4;
    private javax.swing.JButton bt_h5;
    private javax.swing.JButton bt_i1;
    private javax.swing.JButton bt_i2;
    private javax.swing.JButton bt_i3;
    private javax.swing.JButton bt_i4;
    private javax.swing.JButton bt_i5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
